-- AlterTable
ALTER TABLE "Driver" ADD COLUMN     "Latitude" FLOAT8 NOT NULL DEFAULT 0.0;
ALTER TABLE "Driver" ADD COLUMN     "LocationName" STRING NOT NULL DEFAULT '';
ALTER TABLE "Driver" ADD COLUMN     "Longitude" FLOAT8 NOT NULL DEFAULT 0.0;
